name: Check PR title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  title-checker:
    name: Check PR title
    runs-on: ubuntu-latest
    
    steps:
      - name: Conventional title checker
        uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  check_semver_labels:
    name: Check Semver labels
    runs-on: ubuntu-latest

    steps:
      - name: Check for Semver labels
        uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: major,minor,patch
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  check_cc_labels:
    name: Check conventional commits labels
    runs-on: ubuntu-latest

    steps:
      - uses: danielchabr/pr-labels-checker@v3.1
        with:
          hasSome: feature,fix,bug,changed,deprecated,removed,security,docs,documentation,dependencies
          githubToken: ${{ secrets.GITHUB_TOKEN }}
