name: Update Changelog

on:
  release:
    types:
      - released

jobs:
  update:
    name: Update Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs(changelog): update changelog [skip ci]'
          file_pattern: CHANGELOG.md

  bump-version:
    name: Bump package.json version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Automated Version Bump
        uses: pocket-apps/action-update-version@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'ci: update version to v%version% [skip ci]'
